name: molgpka2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - jupyter
  - pytorch=1.13.1
  - scikit-learn
  - scikit-learn-intelex
  - numpy
  - pandas
  - pip:
    - rdkit
    - py3Dmol
    - torch-geometric
    - requests
